const PERMISSION_DEFINITIONS = [
  {
    code: 'dashboard.view',
    module: 'DASHBOARD',
    name: 'Ver dashboard',
    description: 'Permite visualizar el panel de indicadores generales.',
  },
  {
    code: 'users.create',
    module: 'USERS',
    name: 'Crear usuarios',
    description: 'Permite registrar nuevos usuarios en el sistema.',
  },
  {
    code: 'users.view',
    module: 'USERS',
    name: 'Ver usuarios',
    description: 'Permite consultar el listado de usuarios.',
  },
  {
    code: 'users.roles.manage',
    module: 'USERS',
    name: 'Gestionar roles de usuario',
    description: 'Permite asignar o quitar roles a los usuarios.',
  },
  {
    code: 'users.status.manage',
    module: 'USERS',
    name: 'Gestionar estado de usuario',
    description: 'Permite activar o desactivar cuentas de usuario.',
  },
  {
    code: 'users.permissions.manage',
    module: 'USERS',
    name: 'Configurar permisos por rol',
    description: 'Permite administrar la matriz de permisos de cada rol.',
  },
  {
    code: 'students.view',
    module: 'STUDENTS',
    name: 'Ver alumnos',
    description: 'Permite consultar alumnos y su información académica.',
  },
  {
    code: 'students.manage',
    module: 'STUDENTS',
    name: 'Gestionar alumnos',
    description: 'Permite crear, editar y vincular alumnos.',
  },
  {
    code: 'guardians.view',
    module: 'GUARDIANS',
    name: 'Ver apoderados',
    description: 'Permite consultar apoderados registrados.',
  },
  {
    code: 'guardians.manage',
    module: 'GUARDIANS',
    name: 'Gestionar apoderados',
    description: 'Permite crear, editar y eliminar apoderados.',
  },
  {
    code: 'campuses.view',
    module: 'CAMPUSES',
    name: 'Ver sedes',
    description: 'Permite consultar sedes del instituto.',
  },
  {
    code: 'campuses.manage',
    module: 'CAMPUSES',
    name: 'Gestionar sedes',
    description: 'Permite crear, editar y eliminar sedes.',
  },
  {
    code: 'courses.view',
    module: 'COURSES',
    name: 'Ver cursos',
    description: 'Permite consultar cursos y su catálogo.',
  },
  {
    code: 'courses.manage',
    module: 'COURSES',
    name: 'Gestionar cursos',
    description: 'Permite crear, editar cursos y ofertas por sede.',
  },
  {
    code: 'periods.view',
    module: 'CATALOGS',
    name: 'Ver periodos académicos',
    description: 'Permite consultar periodos académicos.',
  },
  {
    code: 'periods.manage',
    module: 'CATALOGS',
    name: 'Gestionar periodos académicos',
    description: 'Permite crear y administrar periodos académicos.',
  },
  {
    code: 'payment_concepts.view',
    module: 'CATALOGS',
    name: 'Ver conceptos de pago',
    description: 'Permite consultar conceptos de pago disponibles.',
  },
  {
    code: 'enrollments.view',
    module: 'ENROLLMENTS',
    name: 'Ver matrículas',
    description: 'Permite consultar matrículas de alumnos.',
  },
  {
    code: 'enrollments.manage',
    module: 'ENROLLMENTS',
    name: 'Gestionar matrículas',
    description: 'Permite crear y actualizar matrículas.',
  },
  {
    code: 'installments.view',
    module: 'ENROLLMENTS',
    name: 'Ver cuotas',
    description: 'Permite consultar cuotas asociadas a matrículas.',
  },
  {
    code: 'installments.manage',
    module: 'ENROLLMENTS',
    name: 'Gestionar cuotas',
    description: 'Permite crear y administrar cuotas.',
  },
  {
    code: 'teachers.view',
    module: 'TEACHERS',
    name: 'Ver docentes',
    description: 'Permite consultar docentes registrados.',
  },
  {
    code: 'teachers.assignments.view',
    module: 'TEACHERS',
    name: 'Ver asignaciones docentes',
    description: 'Permite consultar cursos y horarios asignados a docentes.',
  },
  {
    code: 'teachers.assignments.manage',
    module: 'TEACHERS',
    name: 'Gestionar asignaciones docentes',
    description: 'Permite crear y modificar asignaciones de docentes.',
  },
  {
    code: 'academic.attendance.view',
    module: 'ACADEMIC',
    name: 'Ver asistencias',
    description: 'Permite consultar asistencias registradas.',
  },
  {
    code: 'academic.attendance.manage',
    module: 'ACADEMIC',
    name: 'Gestionar asistencias',
    description: 'Permite registrar y actualizar asistencias.',
  },
  {
    code: 'academic.assessments.view',
    module: 'ACADEMIC',
    name: 'Ver evaluaciones',
    description: 'Permite consultar evaluaciones programadas.',
  },
  {
    code: 'academic.assessments.manage',
    module: 'ACADEMIC',
    name: 'Gestionar evaluaciones',
    description: 'Permite crear evaluaciones.',
  },
  {
    code: 'academic.grades.view',
    module: 'ACADEMIC',
    name: 'Ver notas',
    description: 'Permite consultar notas de alumnos.',
  },
  {
    code: 'academic.grades.manage',
    module: 'ACADEMIC',
    name: 'Gestionar notas',
    description: 'Permite registrar y actualizar notas.',
  },
  {
    code: 'payments.view',
    module: 'PAYMENTS',
    name: 'Ver pagos',
    description: 'Permite consultar el historial de pagos.',
  },
  {
    code: 'payments.manage',
    module: 'PAYMENTS',
    name: 'Gestionar pagos',
    description: 'Permite registrar pagos y cambiar su estado.',
  },
  {
    code: 'payments.audit.view',
    module: 'PAYMENTS',
    name: 'Ver auditoría de pagos',
    description: 'Permite consultar auditoría de cambios de pagos.',
  },
  {
    code: 'cash_register.view',
    module: 'CASH_REGISTER',
    name: 'Ver caja',
    description: 'Permite consultar sesiones, servicios y movimientos de caja.',
  },
  {
    code: 'cash_register.manage',
    module: 'CASH_REGISTER',
    name: 'Gestionar caja',
    description: 'Permite abrir, cerrar caja y registrar operaciones de servicios.',
  },
  {
    code: 'reports.view',
    module: 'REPORTS',
    name: 'Ver reportes',
    description: 'Permite consultar reportes académicos y financieros.',
  },
  {
    code: 'notifications.view',
    module: 'NOTIFICATIONS',
    name: 'Ver notificaciones',
    description: 'Permite consultar historial de notificaciones.',
  },
  {
    code: 'notifications.manage',
    module: 'NOTIFICATIONS',
    name: 'Gestionar notificaciones',
    description: 'Permite ejecutar procesos de recordatorios por correo.',
  },
];

const DEFAULT_ROLE_PERMISSIONS = {
  ADMIN: PERMISSION_DEFINITIONS.map((permission) => permission.code),
  DIRECTOR: [
    'dashboard.view',
    'users.view',
    'students.view',
    'students.manage',
    'guardians.view',
    'guardians.manage',
    'campuses.view',
    'campuses.manage',
    'courses.view',
    'courses.manage',
    'periods.view',
    'periods.manage',
    'payment_concepts.view',
    'enrollments.view',
    'enrollments.manage',
    'installments.view',
    'installments.manage',
    'teachers.view',
    'teachers.assignments.view',
    'teachers.assignments.manage',
    'academic.attendance.view',
    'academic.attendance.manage',
    'academic.assessments.view',
    'academic.assessments.manage',
    'academic.grades.view',
    'academic.grades.manage',
    'payments.view',
    'payments.manage',
    'payments.audit.view',
    'cash_register.view',
    'cash_register.manage',
    'reports.view',
    'notifications.view',
    'notifications.manage',
  ],
  SECRETARIADO: [
    'dashboard.view',
    'students.view',
    'students.manage',
    'guardians.view',
    'guardians.manage',
    'campuses.view',
    'campuses.manage',
    'courses.view',
    'courses.manage',
    'periods.view',
    'periods.manage',
    'payment_concepts.view',
    'enrollments.view',
    'enrollments.manage',
    'installments.view',
    'installments.manage',
    'teachers.view',
    'teachers.assignments.view',
    'teachers.assignments.manage',
    'academic.attendance.view',
    'academic.attendance.manage',
    'academic.assessments.view',
    'academic.grades.view',
    'payments.view',
    'payments.manage',
    'payments.audit.view',
    'cash_register.view',
    'cash_register.manage',
    'reports.view',
    'notifications.view',
    'notifications.manage',
  ],
  DOCENTE: [
    'dashboard.view',
    'students.view',
    'courses.view',
    'periods.view',
    'teachers.view',
    'teachers.assignments.view',
    'academic.attendance.view',
    'academic.attendance.manage',
    'academic.assessments.view',
    'academic.assessments.manage',
    'academic.grades.view',
    'academic.grades.manage',
  ],
  ALUMNO: [],
};

module.exports = {
  PERMISSION_DEFINITIONS,
  DEFAULT_ROLE_PERMISSIONS,
};
